# Generated by Django 4.1.7 on 2023-03-05 04:23

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "device_id",
                    models.CharField(
                        max_length=256,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Device ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(max_length=256, verbose_name="Device name"),
                ),
                ("location", models.CharField(max_length=256, verbose_name="Location")),
                ("unit", models.CharField(max_length=256, verbose_name="Unit")),
                ("sample_rate", models.FloatField(verbose_name="Sample rate")),
            ],
        ),
        migrations.CreateModel(
            name="TimeSerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("value", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries",
                        to="timescaledbapp.channel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="channel",
            name="measure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="channels",
                to="timescaledbapp.measure",
            ),
        ),
    ]
