# Generated by Django 4.1.7 on 2023-03-03 03:09

from django.db import migrations, models
import timescale.db.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnotherMetricFromTimeScaleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("value", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("temperature", models.FloatField(default=0.0)),
                ("device", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("temperature", models.FloatField()),
                ("location", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
