# Generated by Django 4.1.7 on 2023-03-05 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timescaledbapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeserie",
            old_name="measure",
            new_name="channel",
        ),
    ]
