# Generated by Django 4.2 on 2023-05-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timescaledbapp', '0002_timescaledb'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together=set(),
        ),
    ]
